### ISSUE TITLE
"No JSON object could be decoded" error 

### ISSUE THREAD

**Issue by FloweryScythe13** [sisitrs2/fileTranslate#1]
I've had no luck getting the project to run on any documents. I am using docs (Russian language) that have been converted to UTF-8 encoding and .txt file type, and the file gets split successfully, but the program croaks in translate.py line 24:
`
translated = trans.translate(string)
`
with error 
`
ValueError: No JSON object could be decoded
`

One of the files I'm using is attached for reference. 
[Manipulating Personality - backup second.txt](https://github.com/sisitrs2/fileTranslate/files/2200283/Manipulating.Personality.-.backup.second.txt)

**Comment by sisitrs2** [comment]
Hi!

Thank you for using fileTranslate.
I fixed it you should try it know and send me an update;) glad i could help.

**Comment by sisitrs2** [comment]
Now*

**Comment by FloweryScythe13** [comment]
I still run into the same error as before your fix. I've pasted the stack trace below. This looks like a potentially really helpful program and it would be wonderful to have it working against some of these documents. 

`
Large file, please wait (this can take a minute)..

Traceback (most recent call last):
  File "translate.py", line 67, in <module>
    main()
  File "translate.py", line 50, in main
    output = translate_all(path)
  File "translate.py", line 24, in translate_all
    translated = trans.translate(string) #for code readability (temp.read() => s
tring)
  File "C:\ProgramData\Anaconda3\envs\Python27\lib\site-packages\googletrans\cli
ent.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "C:\ProgramData\Anaconda3\envs\Python27\lib\site-packages\googletrans\cli
ent.py", line 81, in _translate
    data = utils.format_json(r.text)
  File "C:\ProgramData\Anaconda3\envs\Python27\lib\site-packages\googletrans\uti
ls.py", line 62, in format_json
    converted = legacy_format_json(original)
  File "C:\ProgramData\Anaconda3\envs\Python27\lib\site-packages\googletrans\uti
ls.py", line 54, in legacy_format_json
    converted = json.loads(text)
  File "C:\ProgramData\Anaconda3\envs\Python27\lib\json\__init__.py", line 339,
in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Anaconda3\envs\Python27\lib\json\decoder.py", line 364, i
n decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Anaconda3\envs\Python27\lib\json\decoder.py", line 382, i
n raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

**Comment by sisitrs2** [comment]
I figured out what was the problem (stupid mistake lol).
Try it now and update me.

**Comment by FloweryScythe13** [comment]
Hmm, now it seems to be putting a read lock on the split-out files that blocks itself. Stack trace below. I know that I don't have the file open in another application like Word or Notepad. 

(Python27) C:\Users\brichem\Machine Learning Projects\InfoWarsApp\fileTranslate-
master>python translate.py
Hello user,
Enter file to translate  path:
C:\Users\brichem\Machine Learning Projects\InfoWarsApp\data\Manipulating Persona
lity - backup second.txt
Large file, please wait (this can take a minute)..
Fixing JSON problems..
Traceback (most recent call last):
  File "translate.py", line 86, in <module>
    main()
  File "translate.py", line 66, in main
    combineFile(path)
  File "C:\Users\brichem\Machine Learning Projects\InfoWarsApp\fileTranslate-mas
ter\FileHandle\combineFile.py", line 15, in combineFile
    os.remove(path + "(" + str(i) + ")" + "." + file_type)
WindowsError: [Error 32] The process cannot access the file because it is being
used by another process: 'C:\\Users\\brichem\\Machine Learning Projects\\InfoWar
sApp\\data\\Manipulating Personality - backup second(1).txt'

**Comment by sisitrs2** [comment]
I am sorry the project was created for Linux distributions. I am starting to work on its compatibility now so I'll just send you a message when I'm finished.
